// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwcltvljeomndlehyfzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53Y2x0dmxqZW9tbmRsZWh5ZnpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMTgzNDksImV4cCI6MjA2ODU5NDM0OX0.7DBXE_oLuFZXcq82AOeTpUwoBfcpfoWH5V_rz2HVX7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});